- name: Check if Homebrew is already installed
  stat:
    path: /usr/local/bin/brew
  register: brew_check_intel

- name: Check if Homebrew is installed on Apple Silicon
  stat:
    path: /opt/homebrew/bin/brew
  register: brew_check_arm

- name: Install Homebrew (if not already installed)
  shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  when: not brew_check_intel.stat.exists and not brew_check_arm.stat.exists
